function OpenSingle(e, o, n, t) { $.colorbox({ opacity: .8, width: o, height: n, transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !0, arrowKey: !1, top: !1, title: t, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").unbind(), $("#cboxClose").click(function () { $.fn.colorbox.close() }) }, onClosed: function () { }, beforeShow: function () { this.wrap.draggable() } }) }
function OpenSingle1(e, o, n, t) { $.colorbox({ opacity: .8, width: o, height: n, transition: "elastic", speed: 50, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !0, arrowKey: !1, top: !1, title: t, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").remove() }, onClosed: function () { }, beforeShow: function () { this.wrap.draggable() } }) }
function OpenSingle2(e, o, n, t) { $.colorbox({ opacity: .8, width: o, height: n, transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !0, arrowKey: !1, top: !1, title: t, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").remove(), $("#cboxClose").unbind(), $("#cboxClose").click(function () { parent.$.colorbox.close() }) }, onClosed: function () { } }) }
function openPrintOut(e, o, n, t) { $.colorbox({ opacity: .8, width: o, height: n, transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !0, arrowKey: !1, top: !1, title: t, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").unbind(), $("#cboxClose").click(function () { parent.$.colorbox.close() }) }, onClosed: function () { }, beforeShow: function () { this.wrap.draggable() } }) }
function Alert1(e, o) { $.colorbox({ opacity: .8, width: "322px", height: "250px", transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !1, arrowKey: !1, top: !1, title: o, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").remove(), $("#cboxClose").unbind(), $("#cboxClose").click(function () { parent.$.colorbox.close() }) }, onClosed: function () { } }) }
function Alert(e, o) { $.colorbox({ opacity: .8, width: "450px", height: "250px", transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !1, arrowKey: !1, top: !1, title: o, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").remove(), $("#cboxClose").unbind(), $("#cboxClose").click(function () { parent.$.colorbox.close() }) }, onClosed: function () { } }) }
function Alertvip(e, o, n, t) { $.colorbox({ opacity: .8, width: o, height: n, transition: "elastic", speed: 100, onOpen: !1, onLoad: !1, onComplete: function () { $("#cboxTitle").on({ mousedown: function (e) { var o = $("#colorbox").offset(), n = e.pageX - o.left, t = e.pageY - o.top; $(document).on("mousemove.drag", function (e) { $("#colorbox").offset({ top: e.pageY - t, left: e.pageX - n }) }) }, mouseup: function () { $(document).unbind("mousemove.drag") } }) }, onCleanup: !1, onClosed: !1, overlayClose: !1, escKey: !1, arrowKey: !1, top: !1, title: t, bottom: !1, left: !1, right: !1, fixed: !1, iframe: !0, href: e, onLoad: function () { $("#cboxClose").remove(), $("#cboxClose").unbind(), $("#cboxClose").click(function () { parent.$.colorbox.close() }) }, onClosed: function () { } }) }
function OnlyClose() { parent.$.colorbox.close() }
function clickEnter(e, o) { return o.keyCode > 0 ? keyCode = event.keyCode : o.which > 0 ? keyCode = o.which : keycode = o.charCode, 13 != keyCode || (document.getElementById(e).focus(), !1) }
function clickEnter_text(e, o) { var n = o.which ? o.which : event.keyCode; return !(46 != n && n > 31 && (n < 48 || n > 57)) && (o.keyCode > 0 ? keyCode = event.keyCode : o.which > 0 ? keyCode = o.which : keycode = o.charCode, 13 != keyCode || (document.getElementById(e).focus(), document.getElementById(e).select(), !1)) }
function isNumberKey(e) { var o = e.which ? e.which : event.keyCode; return !(o > 31 && (o < 48 || o > 57)) }
function isDecimalKey(e) { var o = e.which ? e.which : event.keyCode; return !(46 != o && o > 31 && (o < 48 || o > 57)) }
function onlyNumber(e) { var o = e.which ? e.which : event.keyCode; return o > 47 && o < 58 }
function space_not(e) { return 32 != (e.which ? e.which : event.keyCode) }
function OnTreeNodeClick(e) { var o = window.event != window.undefined ? window.event.srcElement : e.target, n = "input" == o.tagName.toLowerCase() && "checkbox" == o.type; GetParentByTagName("table", o); if (n) { var t = GetParentByTagName("table", o), c = t.nextSibling; c && 1 == c.nodeType && "div" == c.tagName.toLowerCase() && CheckUncheckChildNodes(t.nextSibling, o.checked), CheckUncheckParentNodes(o, o.checked) } }
function CheckUncheckChildNodes(e, o) { for (var n = e.getElementsByTagName("input"), t = n.length, c = 0; c < t; c++) n[c].checked = o }
function CheckUncheckParentNodes(e, o) { var n = GetParentByTagName("div", e).previousSibling; if (n) { var t; t = !!AreAllSiblingsChecked(e); var c = n.getElementsByTagName("input"); if (c.length > 0) { var i = c[0]; i.checked = t, CheckUncheckParentNodes(i, t) } } }
function AreAllSiblingsChecked(e) { for (var o = GetParentByTagName("div", e), n = o.childNodes.length, t = 0, c = 0; c < n; c++) { if (1 == o.childNodes[c].nodeType) if ("table" == o.childNodes[c].tagName.toLowerCase()) o.childNodes[c].getElementsByTagName("input")[0].checked && (t += 1) } return t > 0 }
function GetParentByTagName(e, o) { for (var n = o.parentNode; n.tagName.toLowerCase() != e.toLowerCase() ;) n = n.parentNode; return n }
//function tog(e) { return e ? "addClass" : "removeClass" }
//function gridviewScroll(e, o, n, t) { $(e).gridviewScroll({ width: o.offsetWidth.toFixed(), height: (o.offsetHeight - 10).toFixed(), headerrowcount: n, freezesize: t, barhovercolor: "#3399FF", barcolor: "#3399FF" }) }
function fill_zero(e) { try { e = e.replace(/"/g, "") } catch (e) { } try { e *= 1 } catch (o) { e = 0 } return isNaN(e) ? 0 : isFinite(e) ? e : void 0 }
//$(document).on("input", ".clearable", function () { $(this)[tog(this.value)]("x") }).on("mousemove", ".x", function (e) { $(this)[tog(this.offsetWidth - 18 < e.clientX - this.getBoundingClientRect().left)]("onX") }).on("click", ".onX", function () { $(this).removeClass("x onX").val("").change() });